export const project1 = {
  title: 'SURF MALL',
  buttonlabel1: '//naver.com',
  buttonlabel2: 'github.com/woojungyang/2021-sc-app-32-shop',
  devtools: 'Devtools',
  tool: 'React.js / Node.js / MySQL   SASS / Styled-component',
  comment: '서핑 관련 쇼핑몰',
  comment2: '(판매페이지,관리자페이지)',
  video: require('../../assets/img/23action.mp4').default,
  dark: true,
  primary: true,
  darkText: true,
};
export const project2 = {
  title: 'Management System',
  buttonlabel1: '//naver.com',
  buttonlabel2: '//github.com/woojungyang/2021-sc-app-15-sql',
  devtools: 'Devtools',
  tool: 'Node.js / Vue.js / MySQL / MariaDB/SASS ',
  comment: '도서 관리 시스템',
  comment2: '(도서관리페이지 Node.js/ Vue.js)',
  video: require('../../assets/img/23action.mp4').default,
  dark: true,
  primary: true,
  darkText: true,
};
export const project3 = {
  title: 'Weather App',
  buttonlabel1: '//sc21-app-vue-weather-ywj.web.app',
  buttonlabel2: '//github.com/woojungyang/2021-sc-app-23-vue-weather',
  devtools: 'Devtools',
  tool: ' Vue.js /  SASS ',
  comment: '위치정보를 사용한 날씨어플',
  comment2: '(현재날씨, 주간날씨)',
  video: require('../../assets/img/23action.mp4').default,
  dark: true,
  primary: true,
  darkText: true,
};
export const project4 = {
  title: 'Kakao SearchEngine',
  buttonlabel1: '//naver.com',
  buttonlabel2: '//github.com/woojungyang',
  devtools: 'Devtools',
  tool: 'HTML5 / CSS / JSP',
  comment: 'Developer를 사용한 검색엔진',
  comment2: '(검색엔진)',
  video: require('../../assets/img/23action.mp4').default,
  dark: true,
  primary: true,
  darkText: true,
};
