export const project1 = {
  title: 'SURF MALL',
  buttonlabel1: '//shop.woojungyang.com/admin',
  buttonlabel2: '//github.com/woojungyang/2021-sc-app-32-shop',
  devtools: 'Devtools',
  tool: 'React.js / Redux / React-Router / Node.js / Sequelize  / Styled-component',
  contribution: '기여도 : 100%',
  comment: '서핑 관련 쇼핑몰',
  comment2: '(판매페이지,관리자페이지)',
  video: require('../../assets/img/32action.mp4').default,
  dark: true,
  primary: true,
  darkText: true,
};
export const project2 = {
  title: 'Management System',
  buttonlabel1: '//book.woojungyang.com/book',
  buttonlabel2: '//github.com/woojungyang/2021-sc-app-15-sql',
  devtools: 'Devtools',
  tool: 'Node.js / Vue.js / Vuex / Vue-router / MySQL / MariaDB  ',
  contribution: '기여도 : 100%',
  comment: '도서 관리 시스템',
  comment2: '(도서관리페이지 Node.js/ Vue.js)',
  video: require('../../assets/img/15action.mp4').default,
  dark: true,
  primary: true,
  darkText: true,
};
export const project3 = {
  title: 'Weather App',
  buttonlabel1: '//sc21-app-vue-weather-ywj.web.app',
  buttonlabel2: '//github.com/woojungyang/2021-sc-app-23-vue-weather',
  devtools: 'Devtools',
  tool: ' Vue.js / Vuex / Vue-router / SASS / Firebase',
  contribution: '기여도 : 100%',
  comment: '위치정보를 사용한 날씨어플',
  comment2: '(현재날씨, 주간날씨)',
  video: require('../../assets/img/23action.mp4').default,
  dark: true,
  primary: true,
  darkText: true,
};
export const project4 = {
  title: 'Kakao SearchEngine',
  buttonlabel1: '//search-deploy-ywj.web.app',
  buttonlabel2: '//github.com/woojungyang/Search-deploy',
  devtools: 'Devtools',
  tool: 'HTML5 / CSS / JSP / Kakao Developers / Firebase',
  contribution: '기여도 : 100%',
  comment: 'Developer를 사용한 검색엔진',
  comment2: '(검색엔진)',
  video: require('../../assets/img/11action.mp4').default,
  dark: true,
  primary: true,
  darkText: true,
};
