export const skills = {
  id: 'skills',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  headline: 'Skills',
  description_1: 'HTML',
  percent_1: '80',
  description_2: 'JavaScript',
  percent_2: '70',
  description_3: 'JQuery',
  percent_3: '60',
  description_4: 'Vue.js',
  percent_4: '60',
  description_5: 'React.js',
  percent_5: '60',
  description_6: 'Node.js',
  percent_6: '65',
  description_7: 'MySql',
  percent_7: '65',
  description_7: 'Scss',
  percent_7: '70',
  description_8: 'Styled-Components',
  percent_8: '70',
};
